### ISSUE TITLE
Linux Audio

### ISSUE THREAD

**Issue by rombust** [sphair/ClanLib#115]
Is anyone else having problems with clanSound on Linux? It doesn't play any audio on my Linux Mint.

Tested with Examples/Sound/Sound.

**Comment by dpjudas** [comment]
My guess would be that it is because there's a sound daemon active that they expect all audio to go through.

**Comment by rombust** [comment]
Thanks spot on.  Due to a bug in our configure scripts we were using OSS instead of the newer ALSA.
