### ISSUE TITLE
Old versions

### ISSUE THREAD

**Issue by jose1711** [sphair/ClanLib#117]
Where can one get old versions of `clanlib` like 1.x or 2.x? Thanks.

**Comment by rombust** [comment]
Legacy downloads are no longer available. If I remember correctly, when the ClanLib servers were shut down many years ago, only the latest version was moved over to GitHub. I expect someone will have an archived version somewhere....

**Comment by jose1711** [comment]
Thank you, will resort to archive.org and Debian repositories which still have them.
