### ISSUE TITLE
Setup/Unix/pkgconfig/clanXML.pc.in: Name false

### ISSUE THREAD

**Issue by BlackMage2** [sphair/ClanLib#121]
The name in Setup/Unix/pkgconfig/clanXML.pc.in is false. on line 8 is written: `Name: clanUI`. What is not true..

**Comment by BlackMage2** [comment]
Here is a patch for this:
`--- Setup/Unix/pkgconfig/clanXML.pc.in.orig	2022-03-17 11:40:11.904434393 +0100
+++ Setup/Unix/pkgconfig/clanXML.pc.in	2022-03-17 11:32:29.626098144 +0100
@@ -5,7 +5,7 @@
 libdir=@libdir@
 includedir=${prefix}/include/ClanLib-@LT_RELEASE@
 
-Name: clanUI
+Name: clanXML
 Description: XML support for ClanLib
 Version: @VERSION@
 Requires: clanCore-@LT_RELEASE@ = @VERSION@`

**Comment by rombust** [comment]
Well spotted !!! Fixed. Thank you.

**Comment by BlackMage2** [comment]
fixed in commit b5042f9f99590f8f7703e7b117b529344dc95f81
