### ISSUE TITLE
can't compile Examples/Display_Render/MapMode

### ISSUE THREAD

**Issue by BlackMage2** [sphair/ClanLib#122]
i can't compile the MapMode example. it fails with

> g++ -I Sources -I ./ `pkg-config --cflags clanApp-4.1 clanDisplay-4.1 clanCore-4.1 clanGL-4.1 clanUI-4.1` -pthread -c Sources/options.cpp -o Sources/options.o
> g++ -I Sources -I ./ `pkg-config --cflags clanApp-4.1 clanDisplay-4.1 clanCore-4.1 clanGL-4.1 clanUI-4.1` -pthread -c Sources/app.cpp -o Sources/app.o
> g++ -I Sources -I ./ `pkg-config --cflags clanApp-4.1 clanDisplay-4.1 clanCore-4.1 clanGL-4.1 clanUI-4.1` -pthread -c ../../ThemeAero/Sources/theme.cpp -o ../../ThemeAero/Sources/theme.o
> ../../ThemeAero/Sources/theme.cpp: In static member function ‘static std::shared_ptr<clan::ListBoxView> Theme::create_listbox()’:
> ../../ThemeAero/Sources/theme.cpp:237:55: error: cannot bind non-const lvalue reference of type ‘std::shared_ptr<clan::ScrollBarView>&’ to an rvalue of type ‘std::shared_ptr<clan::ScrollBarView>’
>   237 |         initialize_scrollbar(listbox->scrollbar_x_view(), true);
>       |                              ~~~~~~~~~~~~~~~~~~~~~~~~~^~
> ../../ThemeAero/Sources/theme.cpp:52:72: note:   initializing argument 1 of ‘static void Theme::initialize_scrollbar(std::shared_ptr<clan::ScrollBarView>&, bool)’
>    52 | void Theme::initialize_scrollbar(std::shared_ptr<clan::ScrollBarView> &scrollbar, bool isHorizontal)
>       |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> ../../ThemeAero/Sources/theme.cpp:238:55: error: cannot bind non-const lvalue reference of type ‘std::shared_ptr<clan::ScrollBarView>&’ to an rvalue of type ‘std::shared_ptr<clan::ScrollBarView>’
>   238 |         initialize_scrollbar(listbox->scrollbar_y_view(), false);
>       |                              ~~~~~~~~~~~~~~~~~~~~~~~~~^~
> ../../ThemeAero/Sources/theme.cpp:52:72: note:   initializing argument 1 of ‘static void Theme::initialize_scrollbar(std::shared_ptr<clan::ScrollBarView>&, bool)’
>    52 | void Theme::initialize_scrollbar(std::shared_ptr<clan::ScrollBarView> &scrollbar, bool isHorizontal)
>       |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> make: *** [../../Makefile.conf:23: ../../ThemeAero/Sources/theme.o] Error 1`

g++ 11.2.0 is used

**Comment by rombust** [comment]
It "should" work now, see latest commits
