### ISSUE TITLE
sidebar points to old domain that is now taken over by spam

### ISSUE THREAD

**Issue by TeoTwawki** [sphair/ClanLib#123]
This ceased being used as of 7th February 2018 but the sidebar here on github still points to it.

![image](https://github.com/sphair/ClanLib/assets/6871475/27d2b21e-59b9-4d5f-962d-2edd455e4883)

**Comment by dpjudas** [comment]
@sphair This is only something you can edit, I think. Best to simply remove the reference, I guess.

Can't say I'm surprised some moron on the internet bought the domain name just to use it for spamming. :)

**Comment by sphair** [comment]
Thanks, fixed
