### ISSUE TITLE
Renderbuffer leak

### ISSUE THREAD

**Issue by rombust** [sphair/ClanLib#128]
It appears that the provider is never destroyed in RenderBuffer_Impl  https://github.com/sphair/ClanLib/blob/master/Sources/Display/Render/render_buffer.cpp
```
	class RenderBuffer_Impl
	{
	public:
		RenderBuffer_Impl() : provider(nullptr)
		{
		}

		RenderBufferProvider *provider;
		Size size;
	};

```
Discovered whilst refactoring the code base. I don't use the RenderBuffer class.

**Comment by dpjudas** [comment]
Sounds like a bug indeed.

**Comment by rombust** [comment]
Fixed
