### ISSUE TITLE
ClanLib dedicated server is being removed at end of January

### ISSUE THREAD

**Issue by rombust** [sphair/ClanLib#92]
The payment for the dedicated server hosting the ClanLib web pages will not be renewed in February 2018 (due to inactivity). 

Links to "clanlib.org" in the source should be modified to point to : https://github.com/sphair/ClanLib

**Comment by dpjudas** [comment]
Understandable. Thanks for hosting the pages.

**Comment by rombust** [comment]
The confirmed switch off date is the 7th February 2018.

**Comment by WoLfulus** [comment]
I suggest pointing the DNS to CloudFlare and using the free page rules to redirect it to GitHub.

**Comment by absolutelynothinghere** [comment]
Why not look into [Github Pages](https://pages.github.com/)? You already have the HTML files in the `Documentation` folder, you can turn them into a website with a nice URL like `sphair.github.io/clanlib` for free.
