### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mq1n** [sphair/ClanLib#95]
Hello, Can I move without any change ClanLib's RSA class and dependencies to my project, Does it support ClanLib's license or can i use it only as static lib?

**Comment by rombust** [comment]
You can move and edit the ClanLib source code into different projects.   See https://github.com/sphair/ClanLib/blob/master/COPYING for further details.

Please note the RSA class is experimental. I do not advise using it for mission critical code. It hasn't had extensive security checks
